### ISSUE TITLE
Group tree and rate rule templates must have matching order in kinetic families

### ISSUE THREAD

**Issue by connie** [GreenGroup/RMG-database#65]
As I found in https://github.com/GreenGroup/RMG-database/commit/6ded3d83873564854cc968a9289b5eb16e6da968, the order in which the groups are listed in a reaction template matters, as it must match that of the tree's L1 groups.  Example:

For the kinetic family `H_Abstraction`, the top nodes are `X_H_or_Xrad_H_Xbirad_H_Xtrirad_H` and `Y_rad_birad_trirad_quadrad`.  The order they are listed in the group tree is

    L1:  X_H_or_Xrad_H_Xbirad_H_Xtrirad_H
          L2: .....
    L1: Y_rad_birad_trirad_quadrad
          L2: ....

And all the rate rules must be defined like so:

    label = "X_H_or_Xrad_H_Xbirad_H_Xtrirad_H;Y_rad_birad_trirad_quadrad"

or 

    label = "Subgroup of X_H_or_Xrad_H_Xbirad_H_Xtrirad_H; Subgroup of Y_rad_birad_trirad_quadrad"

I found that the reversed order rate rules defined with the Y_rad subgroup first and then the X_H subgroup are simply not used.  When I reversed the order of the L1 nodes in the tree, we still get a working minimal example in RMG-Py, but we get a completely different model, and an edge that is about 300 reactions smaller.  This indicates to me that this is a hidden error where simply the out of order rate rules are being ignored.  In other words, we need to fix this error and make a unit test to ensure it does not continue occurring.  

There are 2 ways to fix:
1. Algorithmically change RMG-Py to recognize out of order rate rule templates
2. Order them correctly in the raw database

In this situation I advocate for solution 2, because it is more transparent to the user where the groups come from when browsing the database.

**Comment by rwest** [comment]
I agree with solution 2. Order them correctly, and (first) add some checks to the database unit tests.

**Comment by connie** [comment]
Am trying to create database unit test, discovered new error in which entries in the groups can become overwritten if the product template uses the same name as the reactant group but the family is not its own reverse.  i.e. I was getting errors in 1,2_shiftS which upon further inspection, the group entries first loads a top group as the following with index = 1:

    XSYJ
    1 *1 C   u0 {2,S}
    2 *2 S   u0 {1,S} {3,S}
    3 *3 R!H u1 {2,S}

but then later retains it as the group with the index = -1:

    XSYJ
    1 *1 C   u0 {3,S}
    2 *2 S   u1 {3,S}
    3 *3 R!H u0 {1,S} {2,S}

We can end up overwriting entries in the groups in the function `generateProductTemplate()` in `rmgpy/data/kinetics/family.py` , if the productTemplate stored in the top of a `family_name/groups.py` is labeled with the same name as its reactant, but when it's not its own reverse:

    name = "1,2_shiftS/groups"
    template(reactants=["XSYJ"], products=["XSYJ"], ownReverse=False)

Changing this statement to 

    name = "1,2_shiftS/groups"
    template(reactants=["XSYJ"], products=["XYSJ"], ownReverse=False)

Fixes the problem. So I guess a new unit test will be required for this as well..

**Comment by rwest** [comment]
There are probably a lot of silly things we should test for. It's hard to imagine all the possible ways to mess up a database / tree / dictionary etc., but groups not having unique names sounds like one of them!

**Comment by connie** [comment]
I've checked RMG-Java and the ordering of the nodes does not matter in Java.
